import { Candidate } from '@/types/talentPool';

// Placeholder candidates shown behind blur when access is locked
export const PLACEHOLDER_CANDIDATES: Candidate[] = [
    {
        id: 'REF-PH1',
        role: 'Quantitative Trader',
        highlight: 'Built algorithmic trading system generating CHF 12M annual P&L',
        skills: ['Python', 'C++', 'Risk Management'],
        experience: '6 years',
        seniority: 'Senior',
        cantons: ['Geneva'],
        salaryMin: 200000,
        salaryMax: 250000,
        availability: '1 month',
        entryDate: 'Dec 2024',
        education: 'PhD Mathematics, EPFL',
        workPermit: 'eu_citizen',
        languages: ['English', 'French'],
        functionalExpertise: ['Quant', 'Trading'],
        previousRoles: [
            { role: 'Power Trader', duration: '2 years', location: 'Geneva' },
            { role: 'Energy Quant Analyst', duration: '2 years', location: 'London' },
        ],
    },
    {
        id: 'REF-PH2',
        role: 'Energy Trading Analyst',
        highlight: 'Optimized gas procurement strategy saving EUR 3M annually',
        skills: ['Power Markets', 'Excel', 'SQL'],
        experience: '4 years',
        seniority: 'Mid-level',
        cantons: ['Zug'],
        salaryMin: 120000,
        salaryMax: 140000,
        availability: '2 months',
        entryDate: 'Jan 2025',
        education: 'BSc Economics, University of Zurich',
        workPermit: 'eu_citizen',
        languages: ['English', 'German', 'Italian'],
        functionalExpertise: ['Trading', 'Analytics'],
        previousRoles: [
            { role: 'Junior Power Analyst', duration: '2 years', location: 'Milan' },
        ],
    },
    {
        id: 'REF-PH3',
        role: 'Senior Software Engineer',
        highlight: 'Led migration of ETRM platform to cloud, reducing latency by 40%',
        skills: ['Python', 'AWS', 'Kubernetes'],
        experience: '8 years',
        seniority: 'Senior',
        cantons: ['Zurich', 'Remote'],
        salaryMin: 150000,
        salaryMax: 180000,
        availability: 'Immediate',
        entryDate: 'Jan 2025',
        education: 'MSc Computer Science, ETH Zurich',
        workPermit: 'swiss_citizen',
        languages: ['English', 'German'],
        functionalExpertise: ['Backend', 'Cloud'],
        previousRoles: [
            { role: 'ETRM Developer', duration: '3 years', location: 'Zurich' },
            { role: 'Trading Systems Engineer', duration: '2 years', location: 'Munich' },
        ],
    },
    {
        id: 'REF-PH4',
        role: 'Chief Technology Officer',
        highlight: 'Scaled trading technology team from 5 to 45 engineers across 3 offices',
        skills: ['Leadership', 'Architecture', 'Strategy'],
        experience: '15 years',
        seniority: 'Senior',
        cantons: ['Zurich', 'Zug'],
        salaryMin: 280000,
        salaryMax: 350000,
        availability: '3 months',
        entryDate: 'Nov 2024',
        education: 'MBA, IMD Lausanne',
        workPermit: 'swiss_citizen',
        languages: ['English', 'German', 'French'],
        functionalExpertise: ['Tech', 'Management'],
        previousRoles: [
            { role: 'VP Engineering at Energy Trading Firm', duration: '4 years', location: 'Zurich' },
            { role: 'Head of Trading Technology', duration: '3 years', location: 'Berlin' },
            { role: 'Lead Developer at Commodity House', duration: '3 years', location: 'San Francisco' },
        ],
    },
    {
        id: 'REF-PH5',
        role: 'Risk Manager',
        highlight: 'Implemented enterprise-wide risk framework for CHF 2B trading portfolio',
        skills: ['VaR', 'Credit Risk', 'Basel III'],
        experience: '10 years',
        seniority: 'Senior',
        cantons: ['Basel'],
        salaryMin: 160000,
        salaryMax: 190000,
        availability: 'Immediate',
        entryDate: 'Jan 2025',
        education: 'MSc Financial Engineering, HEC Lausanne',
        workPermit: 'c_permit',
        languages: ['English', 'French'],
        functionalExpertise: ['Risk', 'Compliance'],
        previousRoles: [
            { role: 'Commodity Risk Analyst', duration: '4 years', location: 'Basel' },
            { role: 'Market Risk Analyst', duration: '3 years', location: 'Frankfurt' },
        ],
    },
    {
        id: 'REF-PH6',
        role: 'Data Scientist',
        highlight: 'Developed ML model improving power price forecasting accuracy by 25%',
        skills: ['Machine Learning', 'Python', 'TensorFlow'],
        experience: '5 years',
        seniority: 'Mid-level',
        cantons: ['Lausanne', 'Remote'],
        salaryMin: 130000,
        salaryMax: 155000,
        availability: '1 month',
        entryDate: 'Dec 2024',
        education: 'MSc Data Science, EPFL',
        workPermit: 'eu_citizen',
        languages: ['English', 'French', 'Spanish'],
        functionalExpertise: ['Data', 'Analytics'],
        previousRoles: [
            { role: 'Energy Forecasting Analyst', duration: '2 years', location: 'Lausanne' },
            { role: 'Commodity Data Analyst', duration: '1.5 years', location: 'Barcelona' },
        ],
    },
    {
        id: 'REF-PH7',
        role: 'Commodities Analyst',
        highlight: 'Published research cited by Bloomberg on MENA oil supply dynamics',
        skills: ['Fundamentals', 'Bloomberg', 'Research'],
        experience: '3 years',
        seniority: 'Mid-level',
        cantons: ['Geneva'],
        salaryMin: 95000,
        salaryMax: 115000,
        availability: '2 months',
        entryDate: 'Jan 2025',
        education: 'BSc International Relations, University of Geneva',
        workPermit: 'swiss_citizen',
        languages: ['English', 'French', 'Arabic'],
        functionalExpertise: ['Research', 'Analytics'],
        previousRoles: [
            { role: 'Oil & Gas Research Intern', duration: '1 year', location: 'Geneva' },
        ],
    },
    {
        id: 'REF-PH8',
        role: 'Head of Operations',
        highlight: 'Reduced trade settlement errors by 90% through process automation',
        skills: ['Process Optimization', 'Team Leadership', 'SAP'],
        experience: '12 years',
        seniority: 'Senior',
        cantons: ['Zurich'],
        salaryMin: 220000,
        salaryMax: 260000,
        availability: '3 months',
        entryDate: 'Nov 2024',
        education: 'MBA, University of St. Gallen',
        workPermit: 'swiss_citizen',
        languages: ['English', 'German'],
        functionalExpertise: ['Operations', 'Management'],
        previousRoles: [
            { role: 'Trading Operations Manager', duration: '4 years', location: 'Zurich' },
            { role: 'Middle Office Lead', duration: '3 years', location: 'Vienna' },
        ],
    },
];

// Helper to get placeholders for locked view with view-specific limits
export function getPlaceholderCandidates(
    viewMode: 'grid' | 'table',
    isMobile: boolean = false
): Candidate[] {
    // Mobile always shows 1 (table toggle isn't visible on mobile)
    if (isMobile) {
        return PLACEHOLDER_CANDIDATES.slice(0, 1);
    }
    // Desktop: 8 for table, 3 for grid
    return PLACEHOLDER_CANDIDATES.slice(0, viewMode === 'table' ? 8 : 3);
}
