-- ============================================================================
-- Migration: Add profile_bio column to user_profiles
-- ============================================================================
-- Purpose: Store AI-generated professional profile summaries
-- When: After CV parsing completes
-- Generated by: GPT-4o-mini in the parser service
-- ============================================================================

ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS profile_bio TEXT;

COMMENT ON COLUMN user_profiles.profile_bio IS
  'AI-generated professional summary (3-4 sentences). Generated by parser after CV extraction.';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
